site_name: PyKitReWi
site_url: https://rewi.xyz

# 自动文档化的代码路径
nav:
  - Home: index.md
  - Development: develop.md
  - Structure: structure.md
  - PyKitReWi:
      - apps: apps.md
      - sample: sample.md
      - servers: servers.md
      - utils: utils.md
plugins:
  - search  # 启用搜索插件
  - autorefs
  - mkdocstrings:
      enable_inventory: false
      extra_python_path:
        - src  # 添加 src 目录到 Python 路径
  #      enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
  #      custom_templates: templates
  #      default_handler: python
  #      handlers:
  #        python:
  #          options:
  #            show_source: false

theme:
  name: material
#theme: readthedocs
mkdocstrings:
  default:
    style: google  # 或者 numpy, pytorch 等